### ISSUE TITLE
please make deploy to heroku button

### ISSUE THREAD

**Issue by kakamband** [GeoffreyY/nobigfollows#1]
Hi GeoffreyY,
please make this anti bot to deployable to heroku with all env value must be set & heroku buildpacks needed
waiting for your response
finest regards

**Comment by GeoffreyY** [comment]
I've added some description on how to deploy your own instance in the readme: https://github.com/GeoffreyY/nobigfollows#deploying-your-own-instance

I'm not familiar with heroku buildpacks, not sure if you need one at all.

Feel free to ask if you need any more specific information, or any of my description isn't clear. :)

**Comment by GeoffreyY** [comment]
the redirect urls have been changed, and the readme has been updated to reflect the change.
